spring:
  application:
    name: demo

payment:
  type: CRYPTO
  amount: 10000
  mir:
    fee: 0.01
    min-amount: 100
    max-amount: 1000000
    currency: RUB
  crypto:
    fee: 0.001
    min-amount: 100
    max-amount: 1000000
    currency: USDT